### ISSUE TITLE
Is this the active version of this project?

### ISSUE THREAD

**Issue by vringar** [datlowe/gradle-maven-publish-auth#1]
Hey,
I'm trying to use this plugin and am wondering are you the new maintainer of this project and would you like me to make a PR against the original repo to redirect to yours?

**Comment by dedekj** [comment]
Hi Stefan, 
no I don't feel like to be a new maintainer, I just wanted to make the plugin working easily and made a simple contribution...

See also:
https://github.com/sebersole/gradle-maven-publish-auth/issues/18
 
Try to contact @sebersole, and discuss it with him...

Maybe you could be the new maintainer ;-)

**Comment by DNAlchemist** [comment]
Can you update your fork and release a new version?

**Comment by dedekj** [comment]
@DNAlchemist 

I'd like to, but it requires some (probably not much) time. This fork is still based on version **before 3.0.0**. I will keep it in my mind and hopefully do it soon.

---
I still use this (old) version quite often and I'm really happy with it :-) What are the most interesting changes in the new version? ...to increase my motivation for the update :-)
Thanks.

**Comment by sebersole** [comment]
The 2 main changes were (1) the ability to authenticate for download repos
as well as for uploads and (2) converting to a proper Gradle plugin in
terms of making it available in the plugin portal.

**Comment by dedekj** [comment]
I tested `"org.hibernate.build.maven-repo-auth" version "3.0.0"` and it is working the same way as this fork. So there is no need to maintain this fork any more. I updated the README and I'm going to archive this repository. We (datlowe) are going to use `org.hibernate.build.maven-repo-auth` instead...

@sebersole Thanks again for this gradle plugin!
